all:
	g++ -O2 -o EP4-PedroPaulo main.cpp ./GrafoPalavras.cpp ./Estruturas/Digrafo.cpp ./Estruturas/Elemento.h ./Estruturas/FilaPrioridades.cpp ./Estruturas/Lista.h ./Estruturas/Par.h ./Estruturas/TabelaHash.h

clean:
	rm -rf *.o EP4-PedroPaulo
